# Generated by Django 5.2.6 on 2025-09-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientdoctormapping',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
            preserve_default=False,
        ),
    ]
